FROM arm32v7/debian:stretch-slim AS builder

COPY qemu-arm-static /usr/bin

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  echo "deb-src http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y --no-install-recommends install apt-utils git ca-certificates libneon27-gnutls-dev ninja-build && \
  apt-get -y --no-install-recommends build-dep mariadb-server openssl libssl-dev zlib1g-dev

ARG MARIADB_VERSION=10.3
RUN git clone --branch $MARIADB_VERSION --single-branch --depth=1 https://github.com/MariaDB/server.git /src

WORKDIR /src

#RUN cmake . -DBUILD_CONFIG=mysql_release && make
RUN cmake . \
  -DCMAKE_BUILD_TYPE=MinSizeRel \
  -DCONC_WITH_UNIT_TESTS=OFF \
  -DENABLED_LOCAL_INFILE=ON \
  -DINSTALL_MYSQLTESTDIR= \
  -DCONC_WITH_{UNITTEST,SSL}=OFF \
  -DWITH_EMBEDDED_SERVER=OFF \
  -DWITH_MARIABACKUP=OFF \
  -DWITH_UNIT_TESTS=OFF \
  -DPLUGIN_ARCHIVE=NO \
  -DPLUGIN_BLACKHOLE=NO \
  -DPLUGIN_CASSANDRA=NO \
  -DPLUGIN_FEDERATED=NO \
  -DPLUGIN_FEDERATEDX=NO \
  -DPLUGIN_MROONGA=NO \
  -DPLUGIN_OQGRAPH=NO \
  -DPLUGIN_PERFSCHEMA=NO \
  -DPLUGIN_SPHINX=NO \
  -DPLUGIN_SPIDER=NO \
  -DPLUGIN_FEEDBACK=NO \
  -DPLUGIN_SQL_ERRLOG=NO \
  -DPLUGIN_DEBUG_KEY_MANAGEMENT=NO \
  -DPLUGIN_AUTH_SOCKET=NO \
  -DPLUGIN_QA_AUTH_INTERFACE=NO \
  -DPLUGIN_QA_AUTH_CLIENT=NO \
  -DPLUGIN_DIALOG_EXAMPLES=NO \
  -DPLUGIN_QUERY_CACHE_INFO=NO \
  -DPLUGIN_EXAMPLE_KEY_MANAGEMENT=NO \
  -DPLUGIN_WSREP_INFO=NO \
  -DPLUGIN_TOKUDB=NO \
  -DPLUGIN_QA_AUTH_SERVER=NO \
  -DPLUGIN_METADATA_LOCK_INFO=NO \
  -DPLUGIN_AUTH_ED25519=NO \
  -DPLUGIN_EXAMPLE=NO \
  -DPLUGIN_FILE_KEY_MANAGEMENT=NO \
  -DPLUGIN_FTEXAMPLE=NO \
  -DPLUGIN_FEDERATEDX=NO \
  -DPLUGIN_SERVER_AUDIT=NO \
  -DPLUGIN_ROCKSDB=NO \
  -DPLUGIN_TEST_SQL_DISCOVERY=NO \
  -DPLUGIN_TEST_VERSIONING=NO \
  -DPLUGIN_DISKS=NO \
  -DPLUGIN_DAEMON_EXAMPLE=NO \
  -DPLUGIN_LOCALES=NO \
  -DPLUGIN_HANDLERSOCKET=NO \
  -DPLUGIN_AUTH_TEST_PLUGIN=NO \
  -DPLUGIN_CLIENT_ED25519=NO \
  -DPLUGIN_CONNECT=NO \
  -DPLUGIN_SIMPLE_PASSWORD_CHECK=NO \
  -DPLUGIN_QUERY_RESPONSE_TIME=NO \
  -DPLUGIN_AUTH_0X0100=NO \
  -DPLUGIN_AUDIT_NULL=NO \
  -DENABLED_PROFILING=OFF \
  -DENABLE_DTRACE=OFF \
  -DENABLE_DEBUG_SYNC=OFF \
  -DWITHOUT_TOKUDB=ON \
  -DWITH_NDB_STORAGE_ENGINE=0 \
  -DWITH_PARTITION_STORAGE_ENGINE=0 \
  -DWITH_OQGRAPH_STORAGE_ENGINE=0 \
  -DWITHOUT_MROONGA_STORAGE_ENGINE=1 \
  -DWITHOUT_ROCKSDB_STORAGE_ENGINE=1 \
  -DWITH_SAFEMALLOC=OFF \
  -DWITH_SSL=system \
  -DWITH_ZLIB=system \
  -G Ninja
